Exercise 1: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10


In [1]:
import numpy as np
a = np.array([[100, 110,], [120, 130] ,[140, 150], [160, 170], [180, 190]])
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Exercise 2: Following is the provided numPy array. return array of items in the third column from all rows
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [2]:
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:,2]

array([33, 66, 99])

Exercise 3: Add the following two NumPy arrays and Modify a result array by calculating the square of each element


arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])


In [3]:
import numpy
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

add = arrayOne + arrayTwo
add

array([[20, 39, 33],
       [25, 25, 28]])

In [14]:
#suare of calulated array
square = add **2
square

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)